apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: argo-redis
  name: argo-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: argo-redis
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
status: {}
